name: Sync to S3

on:
  push:
    branches:
      - main
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SYNC_EXCLUDES: >-
        --exclude ".git/*"
        --exclude ".github/*"
        --exclude "node_modules/*"
        --exclude "docs/**"
        --exclude "*.md"
        --exclude "package*.json"
        --exclude "yarn.lock"
        --exclude ".prettier*"
        --exclude ".eslintrc.*"
        --exclude ".vscode/*"
        --exclude "*.yml"
        --exclude "*.config.js"
        --exclude "*.config.cjs"
        --exclude "*.test.*"
        --exclude "*.log"
        --exclude ".DS_Store"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to S3
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            aws s3 sync . s3://chrisstaub.com ${SYNC_EXCLUDES} --delete
          else
            aws s3 sync . s3://dev.chrisstaub.com ${SYNC_EXCLUDES} --delete
          fi

      - name: Invalidate CloudFront Distribution
        if: github.ref == 'refs/heads/main'
        run: aws cloudfront create-invalidation --distribution-id E2BU3AFPICGS4A --paths "/*"
