name: Sync to S3

on:
  push:
    branches:
      - main
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your region of your bucket

      - name: Sync to S3 (Development)
        if: github.ref == 'refs/heads/development'
        run: aws s3 sync . s3://dev.chrisstaub.com --exclude ".git/*" --exclude "README.md" --exclude ".github/*" --exclude ".gitignore" --exclude "package-lock.json" --exclude "package.json" --exclude "node_modules/*"

      - name: Sync to S3 (Main)
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync . s3://chrisstaub.com --exclude ".git/*" --exclude "README.md" --exclude ".github/*" --exclude ".gitignore" --exclude "package-lock.json" --exclude "package.json"

      - name: Invalidate CloudFront Distribution
        if: github.ref == 'refs/heads/main'
        run: aws cloudfront create-invalidation --distribution-id E2BU3AFPICGS4A --paths "/*"
